language: php

branches:
  only:
    - master
    - development

php:
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install
  - composer self-update

script:
  - phpunit
